### ISSUE TITLE
peer_review with one response

### ISSUE THREAD

**Issue by dmorina** [crowdresearch/daemo-api-client#12]
there is an initialization problem with peer review when only one response is streamed (either when stream=True or when there only one worker doing only one task)

**Comment by shirishgoyal** [comment]
Should we error out if it has single response ?

**Comment by mbernst** [comment]
What did we decide here? I thought it was an error if not including history

**Comment by dmorina** [comment]
yeah, or when we add caching of these responses just notify them but not error

**Comment by shirishgoyal** [comment]
Closed in #28 
Error will be shown if 
a) one response is pushed
b) responses from same worker are pushed as inter_task_review is disabled
