### ISSUE TITLE
Docs and scripting issues

### ISSUE THREAD

**Issue by sharonzhou** [crowdresearch/daemo-api-client#22]
- Specify where to access the Daemo Platform
- Can probably use 2nd person for the platform/interface instructions
- Put in the image of the hill instead: hill sign
- Do I specify price? No mention of price on the tutorial, though the field is required
- Image missing: image:: images/project-options.png
- Comma missing between the tasks in list task_data:

```
task_data = [
    {
        "image_url": "value"
    }
    {
        "image_url": "value"
    }
]
```

**Comment by shirishgoyal** [comment]
Resolved in #23
