### ISSUE TITLE
Don't output "adding tasks..." if the rerun key means we're not actually posting new tasks

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo-api-client#24]
10:34:47 daemo.client: adding tasks...
10:34:49 daemo.client: adding previous worker submissions...

I had a bit of a heart attack thinking it was reposting all my tasks again.

**Comment by shirishgoyal** [comment]
how about "syncing tasks"?

**Comment by shirishgoyal** [comment]
Closed in #28
