### ISSUE TITLE
Rerun seems slow

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo-api-client#25]
My rerun is taking about .5s-1s per previously-completed task. What's the engineering reason this is taking so long? I'd imagine these could be done super quickly, since we cached all the old work at the beginning.

**Comment by mbernst** [comment]
Why I care: debugging takes about 20s per run, even with just 85 tasks completed.

**Comment by dmorina** [comment]
im not sure, one suggestion to speed thing up was to not call the backend again and again if the tasks have been reviewed and nothing has changed

Secondly, all the results are attached to the response of `add_data` call so it might be checking if the task is completed

**Comment by dmorina** [comment]
but I agree, rerun has to be much faster

**Comment by shirishgoyal** [comment]
Resolved by syncing at the onset of the script and getting all data with single API call
