### ISSUE TITLE
Question: if the script throws an exception, should the entire process exit?

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo-api-client#26]
Right now it hangs and you have to Ctrl-C. Typically with Python the uncaught exception actually exits the program.

**Comment by mbernst** [comment]
And it makes it look like I'm doing something wrong when I Ctrl-C:

`10:59:47 daemo.client: channel closed
10:59:47 daemo.client: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
10:59:47 daemo.client: websocket connection lost.
10:59:47 daemo.client: connecting again...`

**Comment by mbernst** [comment]
Also, shouldn't the script exit when the main thread is done?

**Comment by shirishgoyal** [comment]
Resolved
a) backend errors - mturk - cause the script to exit showing up the actual error from mturk
b) websocket connections do not show up as error when closed manually.
c) exceptions caught and displayed as warnings (when handled) or errors(when not handled)
